pkgload::load_all(".",quiet=TRUE)
source("inst/doc-tools/perspective.R")
surface <- synthetic.quadform(2,3,list(diag(c(1,-1))))
points <- sample.synthetic.geometry(surface,synthetic.sampling.uniform.disk(1),n=100,seed=4101)
graph <- create.sknn.graph(points$predictors,k=6,connect.components=FALSE)
dir.create("man/figures",showWarnings=FALSE)
png("man/figures/README-saddle.png",width=1200,height=850,res=150)
par(mar=c(2,1,3,1))
dgraphs_perspective(points$predictors,"Six-neighbor graph on a quadratic saddle",edges=graph.edges(graph))
dev.off()
