test_that("complete reference agrees with analytic and independent graph calculations", {
    X <- cbind(c(0, 1, 2), 0)
    expected <- matrix(c(0, 1, 2, 1, 0, 1, 2, 1, 0), 3)
    expect_equal(fermat.distances(points = X), expected)
    expect_equal(fermat.distances(points = X, rooted = TRUE), sqrt(expected))
    set.seed(710)
    X <- matrix(runif(30), ncol = 2)
    D <- as.matrix(dist(X))
    expect_equal(fermat.distances(points = X, p = 1), unname(D), tolerance = 1e-12)
    g <- igraph::make_full_graph(nrow(X), directed = FALSE)
    e <- igraph::as_edgelist(g, names = FALSE)
    w <- D[e]^2.5
    reference <- unname(igraph::distances(g, weights = w))
    expect_equal(fermat.distances(points = X, p = 2.5), reference)
    expect_equal(fermat.distances(points = X, p = 2.5, graph.type = "sknn", k = nrow(X)-1), reference)
    expect_equal(fermat.distances(points = 3*X, p = 2.5), 3^2.5 * reference)
})

test_that("restriction can change the answer and disconnect pairs", {
    X <- matrix(c(0, 1, 10, 11), ncol = 1)
    complete <- fermat.distances(points = X)
    restricted <- fermat.distances(points = X, graph.type = "sknn", k = 1)
    expect_true(is.finite(complete[1, 4]))
    expect_identical(restricted[1, 4], Inf)
    expect_true(all(restricted >= complete - 1e-12))
    square <- rbind(c(0,0), c(1,0), c(1,1), c(0,1))
    expect_equal(fermat.distances(points = square, p = 1)[1,3], sqrt(2))
    expect_equal(fermat.distances(points = square, p = 1, graph.type = "sknn", k = 2)[1,3], 2)
})

test_that("graph input retains zero edges, isolated vertices, labels and transit vertices", {
    g <- dgraph(list(a=2L, b=c(1L,3L), c=2L, d=integer()),
                list(0, c(0,2), 2, numeric()))
    expect_equal(fermat.distances(g, p=1), graph.geodesic.distances(g))
    expect_equal(unname(fermat.distances(g, vertices=c(3,1))), matrix(c(0,4,4,0),2))
    expect_equal(rownames(fermat.distances(g, vertices=c(3,1))), c("c","a"))
    expect_equal(fermat.distances(g)[1,2], 0)
    expect_identical(fermat.distances(g)[1,4], Inf)
    expect_equal(dim(fermat.distances(g, vertices=integer())), c(0L,0L))
    X <- matrix(c(0,0,1), ncol=1, dimnames=list(c("a","b","c"),NULL))
    expect_equal(fermat.distances(points=X)[1,2], 0)
    expect_equal(fermat.distances(points=X, graph.type="sknn", k=2), fermat.distances(points=X))
    expect_equal(unname(fermat.distances(points=matrix(0,1,1))), matrix(0,1,1))
    g$stages$initial <- g$stages$final
    expect_equal(fermat.distances(g, stage="initial"), fermat.distances(g))
})

test_that("invalid inputs and numeric range failures are explicit", {
    X <- matrix(0:2, ncol=1)
    g <- dgraph(list(2L,1L),list(1,1))
    for (p in list(NA, Inf, 0.5, c(1,2), "2")) expect_error(fermat.distances(points=X,p=p), "'p'")
    expect_error(fermat.distances(points=X,rooted=1), "rooted")
    expect_error(fermat.distances(), "exactly one")
    expect_error(fermat.distances(g,points=X), "exactly one")
    expect_error(fermat.distances(g,k=1), "Construction")
    expect_error(fermat.distances(points=X,k=1), "only accepted")
    expect_error(fermat.distances(points=X,graph.type="sknn"), "k")
    expect_error(fermat.distances(points=X,graph.type="sknn",k=3), "less than")
    expect_error(fermat.distances(points=X,stage="initial"), "final")
    expect_error(fermat.distances(points=matrix(NA,1,1)), "finite numeric")
    expect_error(fermat.distances(points=X,vertices=c(1,1)), "unique")
    expect_error(fermat.distances(dgraph(list(2L,1L))), "base edge lengths")
    expect_error(fermat.distances(points=matrix(c(0,1e200),ncol=1)), "overflow")
    expect_error(fermat.distances(points=matrix(c(0,1e-200),ncol=1)), "underflow")
    expect_error(fermat.distances(dgraph(list(2L,c(1L,3L),2L),list(1e308,c(1e308,1e308),1e308)),p=1), "path-cost overflow")
})
