test_that("geodesic neighbors exclude self and resolve coincident ties by index", {
    X <- cbind(c(0, 0, 1, 2), 0)
    a <- geodesic.knn(X, 1, k.graph = 3)
    expect_equal(a$nn.index[,1], c(2, 1, 1, 3))
    expect_equal(a$nn.dist[,1], c(0, 0, 1, 1))
    expect_equal(a$effective.k, rep(1,4))
    expect_false(any(a$nn.index[,1] == 1:4))
    expect_error(geodesic.knn(X, 4, k.graph=3), "k must")
    expect_error(geodesic.knn(X, 1.5, k.graph=3), "k must")
})
test_that("insufficient components are explicit and never return unreachable vertices", {
    X <- cbind(1:5,0)
    g <- dgraph(list(2L,1L,4L,3L,integer()), list(1,1,1,1,numeric()))
    expect_error(geodesic.knn(X,2,graph=g), "reachable")
    a <- geodesic.knn(X,2,graph=g,small.component="truncate")
    expect_equal(a$effective.k,c(1,1,1,1,0))
    expect_equal(a$nn.index[1:4,1],c(2,1,4,3))
    expect_true(all(is.na(a$nn.index[,2])))
    expect_true(all(is.na(a$nn.dist[5,])))
})
test_that("grid queries keep zero-distance observations and validate requests", {
    grid <- matrix(c(0,0),1)
    X <- rbind(c(0,0),c(1,0))
    a <- geodesic.knnx(X,grid,2,k.graph=1)
    expect_equal(as.vector(a$nn.index),c(1,2))
    expect_equal(as.vector(a$nn.dist),c(0,1))
    expect_error(geodesic.knnx(X,grid,3,k.graph=1),"k must")
    expect_error(geodesic.knnx(X,grid,1,method="knn.graph"),"unused argument")
})
