// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_quadform_geodesics_method
Rcpp::List rcpp_quadform_geodesics_method(Rcpp::NumericMatrix A, Rcpp::NumericVector from, Rcpp::NumericVector to, Rcpp::List domain, std::string method, Rcpp::List control);
RcppExport SEXP _dgraphs_rcpp_quadform_geodesics_method(SEXP ASEXP, SEXP fromSEXP, SEXP toSEXP, SEXP domainSEXP, SEXP methodSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type domain(domainSEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_quadform_geodesics_method(A, from, to, domain, method, control));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_quadform_geodesics_solver
Rcpp::List rcpp_quadform_geodesics_solver(Rcpp::NumericMatrix A, Rcpp::NumericVector from, Rcpp::NumericVector to, Rcpp::List domain, Rcpp::List options);
RcppExport SEXP _dgraphs_rcpp_quadform_geodesics_solver(SEXP ASEXP, SEXP fromSEXP, SEXP toSEXP, SEXP domainSEXP, SEXP optionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type from(fromSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type to(toSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type domain(domainSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type options(optionsSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_quadform_geodesics_solver(A, from, to, domain, options));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_quadform_geodesics_reference_uniforms
Rcpp::List rcpp_quadform_geodesics_reference_uniforms(double seed, int n);
RcppExport SEXP _dgraphs_rcpp_quadform_geodesics_reference_uniforms(SEXP seedSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_quadform_geodesics_reference_uniforms(seed, n));
    return rcpp_result_gen;
END_RCPP
}
