# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
rcpp_quadform_geodesics_method <- function(A, from, to, domain, method, control) {
    .Call(`_dgraphs_rcpp_quadform_geodesics_method`, A, from, to, domain, method, control)
}

#' @keywords internal
#' @noRd
rcpp_quadform_geodesics_solver <- function(A, from, to, domain, options) {
    .Call(`_dgraphs_rcpp_quadform_geodesics_solver`, A, from, to, domain, options)
}

#' @keywords internal
#' @noRd
rcpp_quadform_geodesics_reference_uniforms <- function(seed, n) {
    .Call(`_dgraphs_rcpp_quadform_geodesics_reference_uniforms`, seed, n)
}

