"""Mechanical extraction from immutable phase04; --check verifies generated bytes."""
import argparse
from pathlib import Path

HERE = Path(__file__).resolve().parent
OLD = HERE.parent/'phase04'
p=argparse.ArgumentParser()
p.add_argument('--check',action='store_true')
a=p.parse_args()

def save(name,text):
    path=HERE/name
    if a.check:
        assert path.read_text()==text,name
    else:
        path.write_text(text)

def wrapped(name,start):
    text=(OLD/name).read_text()
    at=text.index(start)
    return text[:at]+'namespace ian::detail {\n'+text[at:]+'\n} // namespace ian::detail\n'

for name,start in [('numeric.hpp','using Json ='),('solver.hpp','struct LPResult'),
                   ('input.hpp','struct Input'),('stages.hpp','Json stages')]:
    save('src/'+name,wrapped(name,start))
for name in ['config.json','IAN-LICENSE.txt','NUMPY-LICENSE.txt']:
    save(name,(OLD/name).read_text())

t=(OLD/'engine.hpp').read_text().replace('#include "checkpoint.hpp"','#include <ian/core.hpp>')
t=t.replace('using Clock = std::chrono::steady_clock;','namespace ian::detail {\nusing Clock = std::chrono::steady_clock;\nstruct ObserverFailure : std::runtime_error { using std::runtime_error::runtime_error; };')
start=t.index('    fs::path out;')
end=t.index('    Mat D, D2;',start)
t=t[:start]+'''    ian::Result &result;
    ian::Observer *observer;
    Mat input_distances;
'''+t[end:]
start=t.index('    Engine(fs::path')
end=t.index('    Json graph_data()',start)
t=t[:start]+'''    Engine(ian::Result &value, ian::Observer *sink, std::string injection)
        : result(value), observer(sink), inject(std::move(injection)) {}
    void emit(Json event) {
        event["iteration"] = iteration;
        event["phase"] = phase;
        if (observer) {
            try { observer->on_event({event.at("event").get<std::string>(), phase, iteration, event.dump()}); }
            catch (const std::exception &e) { throw ObserverFailure(e.what()); }
            catch (...) { throw ObserverFailure("nonstandard_callback_exception"); }
        }
    }
'''+t[end:]
start=t.index('    void checkpoint(')
end=t.index('    Vec solve(',start)
t=t[:start]+'''    void checkpoint(const std::string &stage, const Json &data) {
        ian::Stage which;
        if (stage == "graph") {
            result.graph.edges = edges;
            result.graph.degrees = deg;
            result.graph.internal_upper = upper;
            result.graph.components = components(D.size(), edges);
            result.graph.isolates = isolates(deg);
            result.graph.distance_multiplier = scl;
            for (auto e : edges) result.graph.edge_lengths.push_back(input_distances[e[0]][e[1]]);
            result.graph_valid = true;
            which = ian::Stage::graph;
        } else if (stage == "scales") {
            result.scales = data.at("scales").get<Vec>();
            result.internal_scales = data.at("internal_scales").get<Vec>();
            result.multiplier = C;
            result.scales_valid = true;
            which = ian::Stage::scales;
        } else {
            result.affinity = data.at("affinity").get<Mat>();
            result.affinity_valid = true;
            which = ian::Stage::affinity;
        }
        result.solves = solves;
        result.last_iteration = iteration;
        if (observer) {
            try { observer->on_stage(which, result); }
            catch (const std::exception &e) { throw ObserverFailure(e.what()); }
            catch (...) { throw ObserverFailure("nonstandard_callback_exception"); }
        }
    }
'''+t[end:]
t=t.replace('void run(const Json &input, const fs::path &file)', 'void run(const Json &input)')
t=t.replace('        auto began = Clock::now();\n','')
start=t.index('        metadata = ')
end=t.index('        Json map = p.mapping;',start)
t=t[:start]+'''        result.mapping.representatives = p.mapping["representatives"].get<Ids>();
        result.mapping.member_to_profile = p.mapping["member_to_profile"].get<Ids>();
        result.mapping.specimen_ids = p.mapping["specimen_ids"].get<std::vector<std::string>>();
        result.mapping.profile_ids = p.mapping["profile_ids"].get<std::vector<std::string>>();
        input_distances = p.D;
'''+t[end:]
start=t.index('        status["complete"] = true;')
end=t.index('\n    }\n};',start)
t=t[:start]+'''        result.stats = last_stats;
        result.weighted_stats = final.ratios;
        result.complete = true;
        result.solves = solves;
        result.last_iteration = iteration;'''+t[end:]
save('src/engine.hpp',t+'\n} // namespace ian::detail\n')

io=(OLD/'checkpoint.hpp').read_text().replace('#include "numeric.hpp"','#include <json.hpp>\n#include <stdexcept>')
at=io.index('// File hashes')
io=io[:at]+'''namespace ian::io {
using Json = nlohmann::json;
inline void require(bool condition, const std::string &message) {
    if (!condition) throw std::runtime_error(message);
}
'''+io[at:]+'\n} // namespace ian::io\n'
save('src/checkpoint.hpp',io)
print('Extraction matches accepted numeric/solver/stage bodies and declared I/O substitutions.' if a.check else 'Extracted private implementation and existing file adapter.')
